const actionsTypes = {
    FETCH_LISTS_BEGIN: "FETCH_LISTS_BEGIN",
    FETCH_LISTS_SUCCESS: "FETCH_LISTS_SUCCESS",
    FETCH_LISTS_FAILURE: "FETCH_LISTS_FAILURE",
    ADD_LIST_BEGIN: "ADD_LIST_BEGIN",
    ADD_LIST_SUCCESS: "ADD_LIST_SUCCESS",
    ADD_LIST_FAILURE: "ADD_LIST_FAILURE",
    REMOVE_LIST_BEGIN: "REMOVE_LIST_BEGIN",
    REMOVE_LIST_SUCCESS: "REMOVE_LIST_SUCCESS",
    REMOVE_LIST_FAILURE: "REMOVE_LIST_FAILURE",
    EDIT_LIST_BEGIN: 'EDIT_LIST_BEGIN',
    EDIT_LIST_SUCCESS: 'EDIT_LIST_SUCCESS',
    EDIT_LIST_FAILURE: 'EDIT_LIST_FAILURE'
}

export {actionsTypes}