const actionsTypes = {
    FETCH_STEP_BEGIN: "FETCH_STEP_BEGIN",
    FETCH_STEP_SUCCESS: "FETCH_STEP_SUCCESS",
    FETCH_STEP_FAILURE: "FETCH_STEP_FAILURE",
    ADD_STEP_BEGIN: "ADD_STEP_BEGIN",
    ADD_STEP_SUCCESS: "ADD_STEP_SUCCESS",
    ADD_STEP_FAILURE: "ADD_STEP_FAILURE",
    EDIT_STEP_BEGIN: "EDIT_STEP_BEGIN",
    EDIT_STEP_SUCCESS: "EDIT_STEP_SUCCESS",
    EDIT_STEP_FAILURE: "EDIT_STEP_FAILURE",
    DELETE_STEP_BEGIN: "DELETE_STEP_BEGIN",
    DELETE_STEP_SUCCESS: "DELETE_STEP_SUCCESS",
    DELETE_STEP_FAILURE: "DELETE_STEP_FAILURE"
}

export {actionsTypes}