const actionsTypes = {
    ADD_TASK_BEGIN: "ADD_TASK_BEGIN",
    ADD_TASK_SUCCESS: "ADD_TASK_SUCCESS",
    ADD_TASK_FAILURE: "ADD_TASK_FAILURE",
    FETCH_TASK_BEGIN: "FETCH_TASKBYID_BEGIN",
    FETCH_TASK_SUCCESS: "FETCH_TASKBYID_SUCCESS",
    FETCH_TASK_FAILURE: "FETCH_TASKBYID_FAILURE",
    EDIT_TASK_BEGIN: "EDIT_TASK_BEGIN",
    EDIT_TASK_SUCCESS: "EDIT_TASK_SUCCESS",
    EDIT_TASK_FAILURE: "EDIT_TASK_FAILURE",
    REMOVE_TASK_BEGIN: "REMOVE_TASK_BEGIN",
    REMOVE_TASK_SUCCESS: "REMOVE_TASK_SUCCESS",
    REMOVE_TASK_FAILURE: "REMOVE_TASK_FAILURE"
}

export {actionsTypes}