const actionsTypes = {
    FETCH_TASK_BEGIN: "FETCH_TASK_BEGIN",
    FETCH_TASK_SUCCESS: "FETCH_TASK_SUCCESS",
    FETCH_TASK_FAILURE: "FETCH_TASK_FAILURE",
    FETCH_TASK_BY_DATE_BEGIN: "FETCH_TASK_BY_DATE_BEGIN",
    FETCH_TASK_BY_DATE_SUCCESS: "FETCH_TASK_BY_DATE_SUCCESS",
    FETCH_TASK_BY_DATE_FAILURE: "FETCH_TASK_BY_DATE_FAILURE"
}

export {actionsTypes}